### ISSUE TITLE
Leak of <i> from header strip affects entire page

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/buy.ubuntu.com#1]
Using Firefox 59.0b11 on Ubuntu 17.10 accessing https://buy.ubuntu.com/collections/ubuntu-advantage-for-virtual-guests but also https://buy.ubuntu.com/collections/ubuntu-advantage-for-servers 

On the product pages, there's a parenthetical about Z-systems and LinuxONE which has incorrectly formed HTML, and instead of `<i>(Contact sales@canonical.com for support on IBM z Systems and LinuxONE)</i>` it's `<i>(Contact sales@canonical.com for support on IBM z Systems and LinuxONE)<i>` (note the lack of `</i>`). This causes the rest of the page to be rendered using italics, which is obviously undesirable.

Example screenshot showing this: https://screenshots.firefox.com/4IowuUq0pukmgIQk/buy.ubuntu.com

**Comment by tbille** [comment]
Shopify is amazing. lol
done
