### ISSUE TITLE
Final design pass

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/buy.ubuntu.com#26]

**Comment by anasereijo** [comment]
## General

- [x] make sure text is `#111111` and not `black` across all website

- [x] @matthewpaulthomas what do you think about the size of the buttons (add to cart)? They are much bigger than what we have on vanilla. Is this something you think we should keep?

## Navigation

- [x] I briefed brand to create an svg version of the logo

**Shopping cart**
- [x] Can we use [this shopping cart](https://assets.ubuntu.com/v1/a32d17e3-shopping-cart-white.svg) instead? `height: 26px;` and make sure it's `.u-vertically-center`

- [x] change the red circle to ubuntu orange instead `#e95420`: probably this needs to be smaller as I made the icon smaller too. I will need to see it in situ to tell you the correct size

![Screenshot 2019-10-07 at 16 26 22](https://user-images.githubusercontent.com/36884067/66326022-32adff80-e920-11e9-849f-3e290dd4ede1.png)

## Footer

- [ ] can we check the baseline of this:

![Canonical-Staging (2)](https://user-images.githubusercontent.com/36884067/66204268-67148800-e6a2-11e9-8e74-f6ee5b849cc1.png)

## Front page

- [x] **Hero:** could we use one of [suru strips](https://ubuntu.com/_docs/strips)? If not possible or too complicated, let me know and I'll save an image for you.

- [x] **"Security, compliance and support..." section**: copy is missing, check @matthewpaulthomas [copydoc](https://docs.google.com/document/d/1PI12dk533l4Q3_vW-rpe7bcUpdn9ibp7BCHsxKxSQC4/edit#).

Visual changes here:
![1 buy](https://user-images.githubusercontent.com/36884067/66203837-3f70f000-e6a1-11e9-805c-c0e3d08d146d.png)

- [x] Logo cloud update text as per copy doc

- [x] create "Also available" section below logo clouds as per copydoc

**Delivered by Canonical:**

- [x] delete illustration

- [x] replace logo with [svg version](https://assets.ubuntu.com/v1/3c7954dd-logo-canonical-white.svg) and make it 27px tall

## Essential page

- [x] **Hero section**: white background

**Pricing section**: 

- [x] `light-grey background`

- [x] remove the `--highlighted` from the cards

- [ ] move 'Virtual Server' to the 2nd line of text

- [x] @matthewpaulthomas do you want the lists to be horizontally aligned? If so we'll have that gap between text and list in the 2 first cards

![66223442-693f0c80-e6cb-11e9-9bc8-02a9b09a2f27 png  2422×2424 ](https://user-images.githubusercontent.com/36884067/66321875-283c3780-e919-11e9-8779-9e0c9fe43e33.png)


## Ubuntu Advantage for Desktop

- [x] **Hero section**: white background

**Pricing section**: 

- [x] `light-grey background`

- [x] remove the `--highlighted` from the cards

- [x] the copy doesn't seem to match the [copydoc](https://docs.google.com/document/d/1Ypf66YyJfsch-jJgVkRpYLv2XnDdvumvFLqSUAhZyMY/edit) @matthewpaulthomas should @sowasred2012 look at your wireframe or your copydoc? 

- [x] On @matthewpaulthomas [copydoc](https://docs.google.com/document/d/1Ypf66YyJfsch-jJgVkRpYLv2XnDdvumvFLqSUAhZyMY/edit) the buttons are at the bottom of the cards but on the example/wireframe they are below the title. Not sure what's the correct version

- [x] more visual changes here (please apply same changes in all pricing cards)

![Ubuntu Advantage for Desktop – Canonical-Staging](https://user-images.githubusercontent.com/36884067/66321695-e9a67d00-e918-11e9-9138-a873ed1009bf.png)

## Virtual Guests page

- [x] **Hero section**: white background

**Pricing section**: 

- [x] `light-grey background`

- [x] remove the `--highlighted` from the cards

- [x] text is not matching the [copydoc](https://docs.google.com/document/d/1kXF8mLI_uZbvthxvajUSAiL7w-10xGBar6UZlgJcTUw/edit)

- [x] delete extra bottom space from each card as per previous comments


## Advantage for Servers page

**Hero section**: 

- [x] white background

- [x] text is not matching the [copydoc](https://docs.google.com/document/d/14cdy1SDw84ari-62MyK-vLRiVqfuwDU3j5W4k925oRs/edit)

- [x] delete pictogram

**Pricing section**: 

- [x] `light-grey background`

- [x] remove the `--highlighted` from the cards

- [x] text is not matching the [copydoc](https://docs.google.com/document/d/14cdy1SDw84ari-62MyK-vLRiVqfuwDU3j5W4k925oRs/edit)

- [x] delete extra bottom space from each card as per previous comments

- [x] delete extra spacing below 'IP Legal Assurance program' in both cards

**Comment by anasereijo** [comment]
Hi @sowasred2012 and @matthewpaulthomas,

I think there are only 1 or 2 pages left for me to review but in the meantime, you can start having a look at my (previous) comment with suggestions/changes to https://canonical-staging.myshopify.com. If I have more changes, I will post a new comment.

Hope all makes sense, any questions let me know!

**Comment by matthewpaulthomas** [comment]
> - @matthewpaulthomas what do you think about the size of the buttons (add to cart)? They are much bigger than what we have on vanilla. Is this something you think we should keep?

No, that’s fine, I was fully expecting you to request the standard Vanilla size. 

> - @matthewpaulthomas do you want the lists to be horizontally aligned? If so we'll have that gap between text and list in the 2 first cards

Yes.

> - the copy doesn't seem to match the copydoc @matthewpaulthomas should @sowasred2012 look at your wireframe or your copydoc?
> - On @matthewpaulthomas copydoc the buttons are at the bottom of the cards but on the example/wireframe they are below the title. Not sure what's the correct version

I’ve updated [the “desktops” copydoc](https://docs.google.com/document/d/1Ypf66YyJfsch-jJgVkRpYLv2XnDdvumvFLqSUAhZyMY/edit) to match [that section of the design document](https://docs.google.com/document/d/1PI12dk533l4Q3_vW-rpe7bcUpdn9ibp7BCHsxKxSQC4/edit#heading=h.nwkeggtmw6hu). (I didn’t write the copydocs originally.)

> > IP Legal Assurance Program
>
> delete extra space

This probably isn’t possible, because each list item is a fixed height so that all the rows line up. (Normally this would be done with a table, but Shopify doesn’t allow using a table here.)

**Comment by anasereijo** [comment]
@sowasred2012 please take in consideration Matthew's comment above

**Comment by sowasred2012** [comment]
@anasereijo @matthewpaulthomas thanks guys - cracking on with this now 💪

**Comment by anasereijo** [comment]
@sowasred2012 ubuntu advantage logo [here](https://assets.ubuntu.com/v1/8e728653-Ubuntu+Advantage-lockup_wht.svg)

**Comment by sowasred2012** [comment]
@anasereijo I've addressed the feedback in https://github.com/canonical-web-and-design/buy.ubuntu.com/pull/30, except for the these two points:

> move 'Virtual Server' to the 2nd line of text (_Essential page_)
> can we check the baseline of this (_footer text_)

"Virtual Server" is from a product title field in the CMS - it would mean adding HTML to that field, which might make it harder for the marketing team if they need to update it.

The footer text is, similarly, CMS managed - in any case, should lists and paragraphs share baselines? The content in the left column is a list, and in the middle column it's made up of paragraphs.
