### ISSUE TITLE
Broken link to "the community" in Need Help? footer

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/buy.ubuntu.com#3]
Using Firefox 59.0b11 on Ubuntu 17.10 accessing https://buy.ubuntu.com and other pages therein.

The Need Help? section in the footer links to http://community.ubuntu.com/help-information/?_ga=123.456.789 (I eluded the GA id here to protect the innocent, but in a similar form). This in turn seems to cause the redirect that's in place for http://community.ubuntu.com/help-information/ to https://community.ubuntu.com/c/documentation/help-and-information to fail with an "Oops! That page doesn’t exist or is private." from the Discourse.

**Comment by tbille** [comment]
Link updated
