### ISSUE TITLE
Error inicio sesión ubuntu 19.10

### ISSUE THREAD

**Issue by JaviThay** [canonical-web-and-design/buy.ubuntu.com#34]
Buenos días, cuando tengo la instalación completa de ubuntu 19.10 y voy a iniciar sesión me sale un error y tengo que volver a poner la contraseña una y otra vez.

No me deja iniciar sesión a no ser que le de a recuperación del sistema y inicie sesión desde ahi.

**Comment by SirSamTumless** [comment]
Hola,

Utilice el siguiente enlace para encontrar el mejor lugar para reportar esto https://help.ubuntu.com/community/ReportingBugs
