### ISSUE TITLE
Update cart/checkout templates inline with Shopify upgrade

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/buy.ubuntu.com#45]
Shopify are going to upgrade their checkout at the end of February, we need to make sure the custom code we've added to the cart/checkout pages will work with the upgrade, and update them if not.

**Comment by sowasred2012** [comment]
@pmahnke just took a look at this to get a sense of how much work is needed - turns out there's actually nothing for us to do except accept the upgrade. 🎉 

I've previewed and tested the checkout with their [changes](https://help.shopify.com/en/manual/checkout-settings/checkout-upgrade#whats-new-in-shopify-checkout) applied, and the [custom checkout template](https://github.com/canonical-web-and-design/buy.ubuntu.com/blob/master/src/layout/checkout.liquid) we have is still valid, the `.section--billing-address .section__content` element that the [Sufio/VAT script](https://github.com/canonical-web-and-design/buy.ubuntu.com/blob/master/src/layout/checkout.liquid#L55) relies on still exists in the upgraded checkout.

Unless you see any other potential pitfalls, there's no PR needed, so I'll accept the upgrade in Shopify and close this issue.

**Comment by sowasred2012** [comment]
Checkout upgraded

**Comment by pmahnke** [comment]
@sowasred2012 great work, thanks.
